# Generated by Django 4.2.16 on 2024-10-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting_app', '0002_budget_group_active_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_transaction',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
