# Generated by Django 4.2.16 on 2024-10-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting_app', '0003_budget_transaction_active_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_category',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting_app.budget_group'),
        ),
        migrations.AlterField(
            model_name='budget_transaction',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting_app.budget_category'),
        ),
        migrations.AlterField(
            model_name='category_quota',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgeting_app.budget_category'),
        ),
        migrations.AlterUniqueTogether(
            name='category_quota',
            unique_together={('category_id', 'quota_date')},
        ),
    ]
