# Generated by Django 5.1.2 on 2024-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting_app', '0004_alter_budget_category_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_quota',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AlterField(
            model_name='category_quota',
            name='quota_comment',
            field=models.CharField(default='comment', max_length=100),
        ),
    ]
